repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [-l, '100', --profile, black]
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [-l, '100', --target-version, py36]
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: [--max-line-length, '100', --max-doc-length, '100']
    additional_dependencies:
    - flake8-bugbear
    - pep8-naming
