name: Tests

on:
  push:
  schedule:
  - cron: 0 0 * * 0

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        - pypy-3.9
        os:
        - ubuntu-latest
        include:
        - python-version: '3.6'
          os: ubuntu-22.04
          container: python:3.6-slim
        - python-version: '3.7'
          os: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    # Some versions of Python are not longer supported by GitHub Actions.
    # For those, we use a container image and skip the setup-python step.
    # It will be empty and ignored for the other matrix entries.
    container: ${{ matrix.container }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      if: ${{ matrix.container == null }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
    - name: Run tests
      run: |
        pytest
